/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTicketsRouteImport } from './routes/api/tickets'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiReviewIntelligenceRouteImport } from './routes/api/review-intelligence'
import { Route as ApiGroceriesRouteImport } from './routes/api/groceries'
import { Route as ApiCommunityMapRouteImport } from './routes/api/community-map'
import { Route as ApiCommunityRouteImport } from './routes/api/community'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiCommunityActivityRouteImport } from './routes/api/community/activity'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminOperationsRouteImport } from './routes/api/admin/operations'
import { Route as ApiAdminCommunityRouteImport } from './routes/api/admin/community'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsRoute = ApiTicketsRouteImport.update({
  id: '/api/tickets',
  path: '/api/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewIntelligenceRoute = ApiReviewIntelligenceRouteImport.update({
  id: '/api/review-intelligence',
  path: '/api/review-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroceriesRoute = ApiGroceriesRouteImport.update({
  id: '/api/groceries',
  path: '/api/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityMapRoute = ApiCommunityMapRouteImport.update({
  id: '/api/community-map',
  path: '/api/community-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityRoute = ApiCommunityRouteImport.update({
  id: '/api/community',
  path: '/api/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityActivityRoute = ApiCommunityActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ApiCommunityRoute,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOperationsRoute = ApiAdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ApiAdminRoute,
} as any)
const ApiAdminCommunityRoute = ApiAdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => ApiAdminRoute,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ApiAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/availability': typeof AvailabilityRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/emergency': typeof EmergencyRoute
  '/feed': typeof FeedRoute
  '/groceries': typeof GroceriesRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/community': typeof ApiCommunityRouteWithChildren
  '/api/community-map': typeof ApiCommunityMapRoute
  '/api/groceries': typeof ApiGroceriesRoute
  '/api/review-intelligence': typeof ApiReviewIntelligenceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tickets': typeof ApiTicketsRoute
  '/api/admin/community': typeof ApiAdminCommunityRoute
  '/api/admin/operations': typeof ApiAdminOperationsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/community/activity': typeof ApiCommunityActivityRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/availability': typeof AvailabilityRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/emergency': typeof EmergencyRoute
  '/feed': typeof FeedRoute
  '/groceries': typeof GroceriesRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/community': typeof ApiCommunityRouteWithChildren
  '/api/community-map': typeof ApiCommunityMapRoute
  '/api/groceries': typeof ApiGroceriesRoute
  '/api/review-intelligence': typeof ApiReviewIntelligenceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tickets': typeof ApiTicketsRoute
  '/api/admin/community': typeof ApiAdminCommunityRoute
  '/api/admin/operations': typeof ApiAdminOperationsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/community/activity': typeof ApiCommunityActivityRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/availability': typeof AvailabilityRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/emergency': typeof EmergencyRoute
  '/feed': typeof FeedRoute
  '/groceries': typeof GroceriesRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/admin': typeof ApiAdminRouteWithChildren
  '/api/community': typeof ApiCommunityRouteWithChildren
  '/api/community-map': typeof ApiCommunityMapRoute
  '/api/groceries': typeof ApiGroceriesRoute
  '/api/review-intelligence': typeof ApiReviewIntelligenceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tickets': typeof ApiTicketsRoute
  '/api/admin/community': typeof ApiAdminCommunityRoute
  '/api/admin/operations': typeof ApiAdminOperationsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/community/activity': typeof ApiCommunityActivityRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/availability'
    | '/cart'
    | '/chat'
    | '/emergency'
    | '/feed'
    | '/groceries'
    | '/insights'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/api/admin'
    | '/api/community'
    | '/api/community-map'
    | '/api/groceries'
    | '/api/review-intelligence'
    | '/api/search'
    | '/api/tickets'
    | '/api/admin/community'
    | '/api/admin/operations'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/profile'
    | '/api/auth/signup'
    | '/api/community/activity'
    | '/api/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/availability'
    | '/cart'
    | '/chat'
    | '/emergency'
    | '/feed'
    | '/groceries'
    | '/insights'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/api/admin'
    | '/api/community'
    | '/api/community-map'
    | '/api/groceries'
    | '/api/review-intelligence'
    | '/api/search'
    | '/api/tickets'
    | '/api/admin/community'
    | '/api/admin/operations'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/profile'
    | '/api/auth/signup'
    | '/api/community/activity'
    | '/api/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/availability'
    | '/cart'
    | '/chat'
    | '/emergency'
    | '/feed'
    | '/groceries'
    | '/insights'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/api/admin'
    | '/api/community'
    | '/api/community-map'
    | '/api/groceries'
    | '/api/review-intelligence'
    | '/api/search'
    | '/api/tickets'
    | '/api/admin/community'
    | '/api/admin/operations'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/profile'
    | '/api/auth/signup'
    | '/api/community/activity'
    | '/api/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  EmergencyRoute: typeof EmergencyRoute
  FeedRoute: typeof FeedRoute
  GroceriesRoute: typeof GroceriesRoute
  InsightsRoute: typeof InsightsRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAdminRoute: typeof ApiAdminRouteWithChildren
  ApiCommunityRoute: typeof ApiCommunityRouteWithChildren
  ApiCommunityMapRoute: typeof ApiCommunityMapRoute
  ApiGroceriesRoute: typeof ApiGroceriesRoute
  ApiReviewIntelligenceRoute: typeof ApiReviewIntelligenceRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTicketsRoute: typeof ApiTicketsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets': {
      id: '/api/tickets'
      path: '/api/tickets'
      fullPath: '/api/tickets'
      preLoaderRoute: typeof ApiTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-intelligence': {
      id: '/api/review-intelligence'
      path: '/api/review-intelligence'
      fullPath: '/api/review-intelligence'
      preLoaderRoute: typeof ApiReviewIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groceries': {
      id: '/api/groceries'
      path: '/api/groceries'
      fullPath: '/api/groceries'
      preLoaderRoute: typeof ApiGroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community-map': {
      id: '/api/community-map'
      path: '/api/community-map'
      fullPath: '/api/community-map'
      preLoaderRoute: typeof ApiCommunityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community': {
      id: '/api/community'
      path: '/api/community'
      fullPath: '/api/community'
      preLoaderRoute: typeof ApiCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community/activity': {
      id: '/api/community/activity'
      path: '/activity'
      fullPath: '/api/community/activity'
      preLoaderRoute: typeof ApiCommunityActivityRouteImport
      parentRoute: typeof ApiCommunityRoute
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/operations': {
      id: '/api/admin/operations'
      path: '/operations'
      fullPath: '/api/admin/operations'
      preLoaderRoute: typeof ApiAdminOperationsRouteImport
      parentRoute: typeof ApiAdminRoute
    }
    '/api/admin/community': {
      id: '/api/admin/community'
      path: '/community'
      fullPath: '/api/admin/community'
      preLoaderRoute: typeof ApiAdminCommunityRouteImport
      parentRoute: typeof ApiAdminRoute
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof ApiAdminRoute
    }
  }
}

interface ApiAdminRouteChildren {
  ApiAdminCommunityRoute: typeof ApiAdminCommunityRoute
  ApiAdminOperationsRoute: typeof ApiAdminOperationsRoute
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
}

const ApiAdminRouteChildren: ApiAdminRouteChildren = {
  ApiAdminCommunityRoute: ApiAdminCommunityRoute,
  ApiAdminOperationsRoute: ApiAdminOperationsRoute,
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
}

const ApiAdminRouteWithChildren = ApiAdminRoute._addFileChildren(
  ApiAdminRouteChildren,
)

interface ApiCommunityRouteChildren {
  ApiCommunityActivityRoute: typeof ApiCommunityActivityRoute
}

const ApiCommunityRouteChildren: ApiCommunityRouteChildren = {
  ApiCommunityActivityRoute: ApiCommunityActivityRoute,
}

const ApiCommunityRouteWithChildren = ApiCommunityRoute._addFileChildren(
  ApiCommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvailabilityRoute: AvailabilityRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  EmergencyRoute: EmergencyRoute,
  FeedRoute: FeedRoute,
  GroceriesRoute: GroceriesRoute,
  InsightsRoute: InsightsRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAdminRoute: ApiAdminRouteWithChildren,
  ApiCommunityRoute: ApiCommunityRouteWithChildren,
  ApiCommunityMapRoute: ApiCommunityMapRoute,
  ApiGroceriesRoute: ApiGroceriesRoute,
  ApiReviewIntelligenceRoute: ApiReviewIntelligenceRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTicketsRoute: ApiTicketsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
