/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiReviewIntelligenceRouteImport } from './routes/api/review-intelligence'
import { Route as ApiGroceriesRouteImport } from './routes/api/groceries'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewIntelligenceRoute = ApiReviewIntelligenceRouteImport.update({
  id: '/api/review-intelligence',
  path: '/api/review-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroceriesRoute = ApiGroceriesRouteImport.update({
  id: '/api/groceries',
  path: '/api/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/emergency': typeof EmergencyRoute
  '/feed': typeof FeedRoute
  '/groceries': typeof GroceriesRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/groceries': typeof ApiGroceriesRoute
  '/api/review-intelligence': typeof ApiReviewIntelligenceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/emergency': typeof EmergencyRoute
  '/feed': typeof FeedRoute
  '/groceries': typeof GroceriesRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/groceries': typeof ApiGroceriesRoute
  '/api/review-intelligence': typeof ApiReviewIntelligenceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/emergency': typeof EmergencyRoute
  '/feed': typeof FeedRoute
  '/groceries': typeof GroceriesRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/groceries': typeof ApiGroceriesRoute
  '/api/review-intelligence': typeof ApiReviewIntelligenceRoute
  '/api/search': typeof ApiSearchRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/cart'
    | '/chat'
    | '/emergency'
    | '/feed'
    | '/groceries'
    | '/insights'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/api/groceries'
    | '/api/review-intelligence'
    | '/api/search'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/profile'
    | '/api/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/availability'
    | '/cart'
    | '/chat'
    | '/emergency'
    | '/feed'
    | '/groceries'
    | '/insights'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/api/groceries'
    | '/api/review-intelligence'
    | '/api/search'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/profile'
    | '/api/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/cart'
    | '/chat'
    | '/emergency'
    | '/feed'
    | '/groceries'
    | '/insights'
    | '/profile'
    | '/signin'
    | '/signup'
    | '/api/groceries'
    | '/api/review-intelligence'
    | '/api/search'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/profile'
    | '/api/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  EmergencyRoute: typeof EmergencyRoute
  FeedRoute: typeof FeedRoute
  GroceriesRoute: typeof GroceriesRoute
  InsightsRoute: typeof InsightsRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiGroceriesRoute: typeof ApiGroceriesRoute
  ApiReviewIntelligenceRoute: typeof ApiReviewIntelligenceRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-intelligence': {
      id: '/api/review-intelligence'
      path: '/api/review-intelligence'
      fullPath: '/api/review-intelligence'
      preLoaderRoute: typeof ApiReviewIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groceries': {
      id: '/api/groceries'
      path: '/api/groceries'
      fullPath: '/api/groceries'
      preLoaderRoute: typeof ApiGroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  EmergencyRoute: EmergencyRoute,
  FeedRoute: FeedRoute,
  GroceriesRoute: GroceriesRoute,
  InsightsRoute: InsightsRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiGroceriesRoute: ApiGroceriesRoute,
  ApiReviewIntelligenceRoute: ApiReviewIntelligenceRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
